### ISSUE TITLE
Restart and deploy using daemon gives error

### ISSUE THREAD

**Issue by ddineshk** [bmuschko/gradle-cargo-plugin#125] opened 2015-04-30 10:52 UTC
I am trying to restart(stop, start) the container before doing deployment. So I try to use the Cargo Daemon functionality as explained in README file. 

    apply plugin: 'com.bmuschko.cargo'
    cargo {
    ...
    }
    ext.tomcat7HandleId = 'tomcat7'
    task cargoDaemonStop(type: com.bmuschko.gradle.cargo.tasks.daemon.CargoDaemonStop) {
        handleId = tomcat7HandleId
    }
    task cargoDaemonStart(type: com.bmuschko.gradle.cargo.tasks.daemon.CargoDaemonStart) {
          handleId = tomcat7HandleId
    }
    cargoDaemonStart.mustRunAfter cargoDaemonStop
    cargoRedeployRemote.dependsOn cargoDaemonStop, cargoDaemonStart 

But I get the below error 

    Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cargoDaemonStop'.
        at 
     ...
    Caused by: org.gradle.internal.UncheckedException: java.lang.reflect.InvocationTargetException
        at 
     ...
    Caused by: java.lang.reflect.InvocationTargetException
        at     
     ...
    Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/launch/AntMain
        at org.apache.tools.ant.Project.initProperties(Project.java:308)
        at org.apache.tools.ant.Project.init(Project.java:295)
        at org.codehaus.cargo.util.AntUtils.createProject(AntUtils.java:144)
        at org.codehaus.cargo.util.AntUtils.<init>(AntUtils.java:53)
        at org.codehaus.cargo.util.DefaultFileHandler.<init>(DefaultFileHandler.java:98)
        at org.codehaus.cargo.tools.daemon.DaemonClient.<init>(DaemonClient.java:77)
        at org.codehaus.cargo.tools.daemon.DaemonClient.<init>(DaemonClient.java:117)
        ... 58 more

     BUILD FAILED

I have even added ant-launcher jar dependencies. But I still get the error

    dependencies {
	testCompile "junit:junit:3.8.1"
	compile module('org.codehaus.groovy:groovy:1.6.0') {
        dependency('antlr:antlr:2.7.7')
        dependency('commons-cli:commons-cli:1.2')
        module('org.apache.ant:ant:1.7.1') {
            dependencies('org.apache.ant:ant-junit:1.7.1@jar',
                         'org.apache.ant:ant-launcher:1.7.1')
        }
    }
    cargo("org.codehaus.cargo:cargo-core-uberjar:1.4.7","org.codehaus.cargo:cargo-ant:1.4.5","jaxen:jaxen:1.1.1")
    tomcatAnt("org.apache.tomcat:tomcat-catalina-ant:7.0.39")
    }

**Comment by bmuschko** [comment] 2015-04-30 12:13
Sounds like you have conflicting versions the Ant libraries in your classpath. Why do you add Ant as a dependency at all? It's included in Gradle core. Also, you don't necessarily need to define the Cargo libraries. This plugin picks a default version for you out-of-the-box.

**Comment by ddineshk** [comment] 2015-04-30 12:18
I added the Ant dependency since I got `Caused by: java.lang.NoClassDefFoundError: org/apache/tools/ant/launch/AntMain` error. Even when the ant libraries in the classpath are removed, I get the same error.

**Comment by bmuschko** [comment] 2015-04-30 12:33
I will need to be able to play around with an example project. Please provide one on GitHub.

**Comment by ddineshk** [comment] 2015-04-30 14:23
I dont have it on GitHub. Here is the link where you can download it as a zip https://docs.google.com/uc?id=0B4Lro5_VzwsBQkozLWdjaV9GMjg&export=download

**Comment by bmuschko** [comment] 2015-05-24 13:18
I tried to reproduce your issue with the provided project but couldn't. Some comments about your dependency declarations:

- You don't need to assign the Cargo dependencies. They are already assigned by the plugin. If there's not a good reason to pick a specific version of Cargo, you shouldn't assign them. Also, you are mixing different versions of Cargo, 1.4.7 and 1.4.5, which is a bad idea as they might be incompatible.
- The library versions you use are extremely old e.g. Groovy 1.6. Why do you not go for the latest version?
- Why do you use "Client module dependencies" (`module` and `dependency`) instead of relying on transitive dependency management. Using this method will increase the risk of mixing incompatible dependency versions.

I am going to close the issue as I cannot reproduce your issue. I am pretty sure you can condense your dependencies to this:

    dependencies {
        testCompile "junit:junit:3.8.1"
        compile 'org.codehaus.groovy:groovy:1.6.0'
        tomcatAnt "org.apache.tomcat:tomcat-catalina-ant:7.0.+"
    }

**Closed by bmuschko** 2015-05-24 13:18 UTC
